//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCabinetService.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_search
    {
        public int rfid_asset_id { get; set; }
        public string rfid_asset_name { get; set; }
        public string asset_id { get; set; }
        public string notes { get; set; }
        public string parent_location_name { get; set; }
        public int parent_location_id { get; set; }
        public string location_name { get; set; }
        public Nullable<int> location_id { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> still_detected_at_location_timestamp { get; set; }
        public Nullable<int> location_time { get; set; }
        public int still_detected_at_location { get; set; }
        public string parent_category_name { get; set; }
        public int parent_category_id { get; set; }
        public string category_name { get; set; }
        public int category_id { get; set; }
        public int risk { get; set; }
        public string owner_name { get; set; }
        public int owner_id { get; set; }
        public Nullable<int> root_assigned_location_id { get; set; }
        public string root_assigned_location_name { get; set; }
        public int assigned_parent_location_id { get; set; }
        public string assigned_parent_location_name { get; set; }
        public int assigned_location_id { get; set; }
        public string assigned_location_name { get; set; }
        public string active_tag_id { get; set; }
        public int battery_level { get; set; }
        public string passive_tag_id { get; set; }
        public int alert_count { get; set; }
        public bool ppm_active { get; set; }
        public string barcode { get; set; }
        public string serial_number { get; set; }
        public int gs1_department_id { get; set; }
        public string gs1_department_name { get; set; }
        public int asset_type { get; set; }
        public int mapping_enabled { get; set; }
        public bool inuse { get; set; }
        public Nullable<int> route_id { get; set; }
        public string gs1_site_code { get; set; }
        public int asset_status_id { get; set; }
        public string asset_status_name { get; set; }
        public string udf1 { get; set; }
        public string udf2 { get; set; }
        public string udf3 { get; set; }
        public string udf4 { get; set; }
        public string udf5 { get; set; }
        public string udf6 { get; set; }
        public string udf7 { get; set; }
        public string udf8 { get; set; }
        public string udf9 { get; set; }
        public string udf10 { get; set; }
        public int relationship { get; set; }
        public int relationship_status { get; set; }
        public int alarm_active { get; set; }
        public string lot_batch { get; set; }
        public Nullable<System.DateTimeOffset> production_date { get; set; }
        public Nullable<System.DateTimeOffset> expiry_date { get; set; }
        public int inspections_due { get; set; }
        public bool gs1_asset { get; set; }
    }
}
